# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2018-03-23 12:06
from __future__ import unicode_literals

import ckeditor_uploader.fields
from django.db import migrations, models
import django.db.models.deletion
import versatileimagefield.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('oauth', '0001_initial'),
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='News',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=128)),
                ('cover', versatileimagefield.fields.VersatileImageField(blank=True, help_text='Upload high quality image to use as cover photo.', null=True, upload_to='news_%Y')),
                ('content', ckeditor_uploader.fields.RichTextUploadingField()),
                ('date', models.DateField()),
                ('author', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='oauth.UserProfile')),
                ('club', models.ForeignKey(blank=True, default=None, help_text='Leave blank to make this a general news.', null=True, on_delete=django.db.models.deletion.CASCADE, to='main.Club')),
            ],
            options={
                'verbose_name_plural': 'news',
                'ordering': ['-date'],
            },
        ),
        migrations.CreateModel(
            name='Update',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=128)),
                ('content', ckeditor_uploader.fields.RichTextUploadingField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
