# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2018-03-23 12:06
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64)),
                ('description', models.TextField()),
                ('location', models.CharField(max_length=64)),
                ('date', models.DateTimeField()),
                ('published', models.BooleanField(default=True)),
                ('club', models.ForeignKey(blank=True, default=None, help_text='Leave blank to make this a general event.', null=True, on_delete=django.db.models.deletion.CASCADE, to='main.Club')),
            ],
            options={
                'ordering': ['date'],
            },
        ),
    ]
