# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2018-03-23 12:06
from __future__ import unicode_literals

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import versatileimagefield.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SocialLink',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('social_media', models.CharField(choices=[('FB', 'Facebook'), ('TW', 'Twitter'), ('LI', 'LinkedIn'), ('GP', 'Google Plus'), ('IG', 'Instagram'), ('GH', 'GitHub'), ('YT', 'YouTube')], max_length=2)),
                ('link', models.URLField()),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['social_media'],
            },
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email_confirmed', models.BooleanField(default=False)),
                ('gender', models.CharField(choices=[('M', 'Male'), ('F', 'Female'), ('T', 'Transgender')], default='M', max_length=1)),
                ('roll', models.CharField(max_length=15, unique=True)),
                ('dob', models.DateField()),
                ('prog', models.CharField(choices=[('BT', 'B.Tech'), ('MT', 'M.Tech'), ('MSc', 'M.Sc'), ('PhD', 'PhD')], default='BT', max_length=5, verbose_name='programme')),
                ('year', models.CharField(choices=[('1', 'First Year'), ('2', 'Second Year'), ('3', 'Third Year'), ('4', 'Fourth Year'), ('5', 'Fifth Year')], default='1', max_length=1)),
                ('phone', models.CharField(max_length=10, validators=[django.core.validators.RegexValidator('^[0-9]{10}$', message='Not a valid number!')])),
                ('avatar', versatileimagefield.fields.VersatileImageField(blank=True, null=True, upload_to='avatar')),
                ('cover', versatileimagefield.fields.VersatileImageField(blank=True, null=True, upload_to='cover')),
                ('hometown', models.CharField(blank=True, max_length=128, null=True)),
                ('branch', models.CharField(choices=[('CSE', 'Computer Science and Engineering'), ('EE', 'Electrical Engineering'), ('ME', 'Mechanical Engineering'), ('CH', 'Chemistry'), ('MA', 'Mathematics'), ('PHY', 'Physics'), ('HSS', 'Humanities and Social Sciences'), ('BBE', 'Biosciences and Bioengineering'), ('BISS', 'BISS'), ('SS', 'SS')], max_length=5)),
                ('skills', models.TextField(blank=True, default=None, help_text='Enter your skills, separated by comma.', max_length=1024, null=True)),
                ('about', models.TextField(blank=True, max_length=160, null=True, verbose_name='about you')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
