# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2018-03-23 12:06
from __future__ import unicode_literals

import ckeditor_uploader.fields
from django.db import migrations, models
import django.db.models.deletion
import hitcount.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('oauth', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Answer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', ckeditor_uploader.fields.RichTextUploadingField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='oauth.UserProfile', verbose_name='author of answer')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Topic',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(choices=[('Q', 'Question'), ('F', 'Feedback')], default='Q', max_length=3)),
                ('title', models.CharField(max_length=256)),
                ('content', ckeditor_uploader.fields.RichTextUploadingField()),
                ('tags', models.CharField(blank=True, default=None, max_length=50, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('slug', models.SlugField(blank=True, unique=True)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='oauth.UserProfile', verbose_name='author of topic')),
                ('upvotes', models.ManyToManyField(blank=True, related_name='topic_upvotes', to='oauth.UserProfile')),
            ],
            options={
                'ordering': ['-created_at'],
            },
            bases=(models.Model, hitcount.models.HitCountMixin),
        ),
        migrations.AddField(
            model_name='answer',
            name='topic',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='forum.Topic', verbose_name='topic of answer'),
        ),
        migrations.AddField(
            model_name='answer',
            name='upvotes',
            field=models.ManyToManyField(blank=True, related_name='answer_upvotes', to='oauth.UserProfile'),
        ),
    ]
